namespace: hello-app
env:
  appEnv: prod

replicaCount: 2

image:
  repository: ghcr.io/kunle-12/aks-cluster
  tag: "sha-PLACEHOLDER"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: hello-app.local
