apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: hello-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
